<?php declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Webkernel core authentication and session tables.
 *
 * ── ID strategy ──────────────────────────────────────────────────────────────
 * All primary keys are custom string identifiers generated by
 * webkernel_id_generator() (cuid2 by default). This replaces sequential
 * auto-increment integers (1, 2, 3 …) which are predictable, easily
 * enumerable, and leak row counts. String IDs are also portable across
 * SQLite, MySQL and PostgreSQL without engine-specific sequences.
 *
 * ── Connection strategy ──────────────────────────────────────────────────────
 * This migration targets 'webkernel_sqlite' — the central SQLite file that
 * Webkernel uses for its own bootstrap, installer, and privilege system.
 */
return new class extends Migration
{
    protected $connection = 'webkernel_sqlite';

    private const ID_LENGTH = 26;

    public function up(): void
    {
        // ── users ─────────────────────────────────────────────────────────────
        Schema::connection($this->connection)->create('users', function (Blueprint $table): void {
            // Custom string PK — generated by webkernel_id_generator (cuid2).
            $table->char('id', self::ID_LENGTH)->primary();

            $table->string('name');
            $table->string('email')->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->rememberToken();

            // Filament HasAvatar
            $table->string('avatar_url')->nullable();

            // Filament MFA — app (TOTP)
            $table->text('app_authentication_secret')->nullable();
            $table->text('app_authentication_recovery_codes')->nullable();

            // Filament MFA — email OTP
            $table->boolean('has_email_authentication')->default(false);

            // Webkernel QuickTouch
            $table->boolean('quick_touch_enabled')->default(true);
            $table->json('quick_touch_favorites')->nullable();

            $table->timestamps();
        });

        // ── user_privileges ───────────────────────────────────────────────────
        // One-to-one with users: each user holds at most one privilege record.
        Schema::connection($this->connection)->create('user_privileges', function (Blueprint $table): void {
            $table->char('id', self::ID_LENGTH)->primary();

            // user_id: unique → one privilege record per user.
            $table->char('user_id', self::ID_LENGTH)
                  ->unique();

            $table->foreign('user_id')
                  ->references('id')
                  ->on('users')
                  ->cascadeOnDelete();

            // The assigned privilege level (enum values stored as strings).
            $table->string('privilege', 30);

            // Internal vs external origin discriminator.
            $table->string('user_origin', 20)->default('internal');

            // Who granted the privilege. Nullable to support self-grant.
            $table->char('granted_by', self::ID_LENGTH)->nullable();

            $table->foreign('granted_by')
                  ->references('id')
                  ->on('users')
                  ->nullOnDelete();

            $table->timestamps();

            // Indexes for common queries.
            $table->index('privilege');
            $table->index('user_origin');
            $table->index(['privilege', 'user_origin']);
            $table->index('granted_by');
        });

        // ── user_password_reset_tokens ─────────────────────────────────────────────
        Schema::connection($this->connection)->create('user_password_reset_tokens', function (Blueprint $table): void {
            $table->string('email')->primary();
            $table->string('token');
            $table->timestamp('created_at')->nullable();
        });

        // ── sessions ──────────────────────────────────────────────────────────
        // Note: sessions.user_id is a string FK referencing users.id.
        // We deliberately do NOT add a DB-level foreign key here because
        // sessions may reference users across different connections.
        Schema::connection($this->connection)->create('sessions', function (Blueprint $table): void {
            $table->string('id')->primary();
            $table->char('user_id', self::ID_LENGTH)->nullable()->index();
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->longText('payload');
            $table->integer('last_activity')->index();
        });
    }

    public function down(): void
    {
        Schema::connection($this->connection)->dropIfExists('sessions');
        Schema::connection($this->connection)->dropIfExists('user_password_reset_tokens');
        Schema::connection($this->connection)->dropIfExists('user_privileges');
        Schema::connection($this->connection)->dropIfExists('users');
    }
};
