<?php

// @formatter:off
// phpcs:ignoreFile
/**
 * A helper file for your Eloquent Models
 * Copy the phpDocs from this file to the correct Model,
 * And remove them from this file, to prevent double declarations.
 *
 * @author Barry vd. Heuvel <barryvdh@gmail.com>
 */


namespace Webkernel\Businesses\Models{
/**
 * Organisation — the multi-tenant unit of a Webkernel instance.
 *
 * Each Organisation is an isolated namespace. It is owned by the App Owner
 * at the infrastructure level but managed day-to-day by its Org-Admin.
 *
 * The App Owner creates Organisations; they never map directly to one.
 * This separation keeps infrastructure authority out of organisational scope.
 *
 * @property string                $id            cuid2 string PK
 * @property string                $name          Display name
 * @property string                $slug          URL-safe unique identifier
 * @property OrganisationStatus    $status        pending | active | suspended
 * @property string                $org_admin_email  Invited Org-Admin email
 * @property string|null           $created_by    FK → users.id (App Owner or Super-User)
 * @property-read User|null        $creator       The user who created this org
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder<static> active()
 * @method static \Illuminate\Database\Eloquent\Builder<static> pending()
 * @method static \Illuminate\Database\Eloquent\Builder<static> forSlug(string $slug)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|Organisation newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|Organisation newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|Organisation query()
 * @mixin \Eloquent
 */
	#[\AllowDynamicProperties]
	class IdeHelperOrganisation {}
}

namespace Webkernel\Users\Models{
/**
 * Webkernel core User model.
 *
 * Primary key strategy
 * ────────────────────
 * The `id` column is a custom string identifier generated by
 * webkernel_id_generator() (cuid2 by default). This avoids sequential
 * integer IDs (1, 2, 3 …) which are predictable, easily enumerable, and
 * leak row counts. String IDs are portable across any database engine.
 *
 * Connection
 * ──────────
 * The model targets 'webkernel_sqlite' by default (the Webkernel core
 * connection). When an app owner selects a different primary database
 * (e.g. PostgreSQL) the connection can be overridden at the config level
 * without touching this model.
 *
 * @property string                          $id
 * @property string                          $name
 * @property string                          $email
 * @property string|null                     $avatar_url
 * @property \Illuminate\Support\Carbon|null $email_verified_at
 * @property string                          $password
 * @property string|null                     $remember_token
 * @property string|null                     $app_authentication_secret
 * @property string|null                     $app_authentication_recovery_codes
 * @property bool                            $has_email_authentication
 * @property bool                            $quick_touch_enabled
 * @property array<int, array{url: string, title: string}>|null $quick_touch_favorites
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Webkernel\Users\Models\UserPrivilege|null $privilegeRelation
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection<int, \Illuminate\Notifications\DatabaseNotification> $notifications
 * @property-read int|null $notifications_count
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User query()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereAppAuthenticationRecoveryCodes($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereAppAuthenticationSecret($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereAvatarUrl($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereEmailVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereHasEmailAuthentication($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereQuickTouchEnabled($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereQuickTouchFavorites($value)
 * @mixin \Eloquent
 */
	#[\AllowDynamicProperties]
	class IdeHelperUser {}
}

namespace Webkernel\Users\Models{
/**
 * Represents a single privilege assignment for a user.
 *
 * One-to-one with User: each user may hold at most one privilege record.
 *
 * @property string                $id            Unique identifier (webkernel_id_generator).
 * @property string                $user_id       FK → users.id (custom string ID).
 * @property UserPrivilegeLevel    $privilege     The assigned privilege level.
 * @property UserOrigin            $user_origin   Whether the user is internal or external.
 * @property string|null           $granted_by    FK → users.id of the granting user.
 *                                                NULL means self-granted (first APP_OWNER).
 * @property-read User             $user          The user who holds this privilege.
 * @property-read User|null        $grantedBy     The user who granted this privilege.
 * @method static Builder|static forPrivilege(UserPrivilegeLevel|string $privilege)
 * @method static Builder|static forOrigin(UserOrigin|string $origin)
 * @method static Builder|static appOwners()
 * @method static Builder|static superUsers()
 * @method static Builder|static internalUsers()
 * @method static Builder|static externalUsers()
 * @method static Builder|static selfGranted()
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static Builder<static>|UserPrivilege newModelQuery()
 * @method static Builder<static>|UserPrivilege newQuery()
 * @method static Builder<static>|UserPrivilege query()
 * @method static Builder<static>|UserPrivilege whereCreatedAt($value)
 * @method static Builder<static>|UserPrivilege whereGrantedBy($value)
 * @method static Builder<static>|UserPrivilege whereId($value)
 * @method static Builder<static>|UserPrivilege wherePrivilege($value)
 * @method static Builder<static>|UserPrivilege whereUpdatedAt($value)
 * @method static Builder<static>|UserPrivilege whereUserId($value)
 * @method static Builder<static>|UserPrivilege whereUserOrigin($value)
 * @mixin \Eloquent
 */
	#[\AllowDynamicProperties]
	class IdeHelperUserPrivilege {}
}

