<?php declare(strict_types=1);

namespace Webkernel\Users\Models;

use Database\Factories\UserFactory;
use Filament\Models\Contracts\FilamentUser;
use Filament\Models\Contracts\HasAvatar;
use Filament\Models\Contracts\HasName;
use Filament\Panel;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Database\Eloquent\Attributes\Table;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Webkernel\Traits\HasQuickTouch;
use Webkernel\Users\Enum\UserPrivilegeLevel;
use Webkernel\Users\Models\User\Concerns\HasPrivilegeLevel;

/**
 * Webkernel core User model.
 *
 * Primary key strategy
 * ────────────────────
 * The `id` column is a custom string identifier generated by
 * webkernel_id_generator() (cuid2 by default). This avoids sequential
 * integer IDs (1, 2, 3 …) which are predictable, easily enumerable, and
 * leak row counts. String IDs are portable across any database engine.
 *
 * Connection
 * ──────────
 * The model targets 'webkernel_sqlite' by default (the Webkernel core
 * connection). When an app owner selects a different primary database
 * (e.g. PostgreSQL) the connection can be overridden at the config level
 * without touching this model.
 *
 * @property string                          $id
 * @property string                          $name
 * @property string                          $email
 * @property string|null                     $avatar_url
 * @property \Illuminate\Support\Carbon|null $email_verified_at
 * @property string                          $password
 * @property string|null                     $remember_token
 * @property string|null                     $app_authentication_secret
 * @property string|null                     $app_authentication_recovery_codes
 * @property bool                            $has_email_authentication
 * @property bool                            $quick_touch_enabled
 * @property array<int, array{url: string, title: string}>|null $quick_touch_favorites
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Webkernel\Users\Models\UserPrivilege|null $privilegeRelation
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection<int, \Illuminate\Notifications\DatabaseNotification> $notifications
 * @property-read int|null $notifications_count
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User query()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereAppAuthenticationRecoveryCodes($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereAppAuthenticationSecret($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereAvatarUrl($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereEmail($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereEmailVerifiedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereHasEmailAuthentication($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User wherePassword($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereQuickTouchEnabled($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereRememberToken($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|User whereUpdatedAt($value)
 * @mixin \Eloquent
 * @mixin IdeHelperUser
 */
#[Table('users')]
#[Fillable(['name', 'email', 'password', 'avatar_url'])]
#[Hidden(['password', 'remember_token'])]
class User extends Authenticatable implements
    FilamentUser,
    HasAvatar,
    HasName,
    MustVerifyEmail
{
    /** @use HasFactory<UserFactory> */
    use HasFactory;
    use Notifiable;
    use HasPrivilegeLevel;
    use HasQuickTouch;

    // ── Primary key ───────────────────────────────────────────────────────────

    /**
     * The custom string identifier type (cuid2 via webkernel_id_generator).
     * Auto-increment is disabled; generation happens in the boot() method.
     *
     * @var string
     */
    protected $keyType = 'string';

    /** @var bool */
    public $incrementing = false;

    // ── Connection ────────────────────────────────────────────────────────────

    /**
     * Targets the Webkernel core SQLite connection.
     *
     * Override via config('webkernel.core_connection') or by extending the
     * model, without changing this default.
     *
     * @var string
     */
    protected $connection = 'webkernel_sqlite';

    // ── Boot ──────────────────────────────────────────────────────────────────

    protected static function boot(): void
    {
        parent::boot();

        static::creating(static function (self $model): void {
            if (empty($model->{$model->getKeyName()})) {
                $model->{$model->getKeyName()} = webkernel_id_generator()
                    ->makeUniqueIdentifier()
                    ->using('cuid2')
                    ->get();
            }
        });
    }

    // ── Casts ─────────────────────────────────────────────────────────────────

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at'      => 'datetime',
            'password'               => 'hashed',
            'has_email_authentication' => 'boolean',
            'quick_touch_enabled'    => 'boolean',
            'quick_touch_favorites'  => 'array',
        ];
    }

    // ── FilamentUser ──────────────────────────────────────────────────────────

    /**
     * Gate for panel access.
     *
     * Any user with a valid privilege record (down to EXTERNAL_STAFF, the lowest
     * level) is allowed in. Scope restrictions are enforced at the policy /
     * resource level, not here. No privilege record → deny.
     */
    public function canAccessPanel(Panel $panel): bool
    {
        return $this->hasPrivilegeOrAbove(UserPrivilegeLevel::EXTERNAL_STAFF);
    }

    // ── HasAvatar ─────────────────────────────────────────────────────────────

    public function getFilamentAvatarUrl(): ?string
    {
        return $this->avatar_url ?? null;
    }

    // ── HasName ───────────────────────────────────────────────────────────────

    public function getFilamentName(): string
    {
        return $this->name;
    }
}
