<?php declare(strict_types=1);

namespace Webkernel\Users\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Webkernel\Users\Enum\UserOrigin;
use Webkernel\Users\Enum\UserPrivilegeLevel;

/**
 * Represents a single privilege assignment for a user.
 *
 * One-to-one with User: each user may hold at most one privilege record.
 *
 * @property string                $id            Unique identifier (webkernel_id_generator).
 * @property string                $user_id       FK → users.id (custom string ID).
 * @property UserPrivilegeLevel    $privilege     The assigned privilege level.
 * @property UserOrigin            $user_origin   Whether the user is internal or external.
 * @property string|null           $granted_by    FK → users.id of the granting user.
 *                                                NULL means self-granted (first APP_OWNER).
 * @property-read User             $user          The user who holds this privilege.
 * @property-read User|null        $grantedBy     The user who granted this privilege.
 * @method static Builder|static forPrivilege(UserPrivilegeLevel|string $privilege)
 * @method static Builder|static forOrigin(UserOrigin|string $origin)
 * @method static Builder|static appOwners()
 * @method static Builder|static superUsers()
 * @method static Builder|static internalUsers()
 * @method static Builder|static externalUsers()
 * @method static Builder|static selfGranted()
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static Builder<static>|UserPrivilege newModelQuery()
 * @method static Builder<static>|UserPrivilege newQuery()
 * @method static Builder<static>|UserPrivilege query()
 * @method static Builder<static>|UserPrivilege whereCreatedAt($value)
 * @method static Builder<static>|UserPrivilege whereGrantedBy($value)
 * @method static Builder<static>|UserPrivilege whereId($value)
 * @method static Builder<static>|UserPrivilege wherePrivilege($value)
 * @method static Builder<static>|UserPrivilege whereUpdatedAt($value)
 * @method static Builder<static>|UserPrivilege whereUserId($value)
 * @method static Builder<static>|UserPrivilege whereUserOrigin($value)
 * @mixin \Eloquent
 * @mixin IdeHelperUserPrivilege
 */
class UserPrivilege extends Model
{
    /**
     * The connection name for the model.
     *
     * Defaults to 'webkernel_sqlite' so that the privilege table always
     * lives on the Webkernel core connection. Change here (or override the
     * connection at runtime) when the app owner migrates the core schema to
     * a different database engine (e.g. PostgreSQL).
     *
     * @var string
     */
    protected $connection = 'webkernel_sqlite';

    protected $table = 'user_privileges';

    /**
     * Primary key type is a custom string ID generated by webkernel_id_generator().
     * Auto-increment is disabled; the model boot method handles generation.
     */
    protected $keyType = 'string';

    public $incrementing = false;

    protected $fillable = [
        'id',
        'user_id',
        'privilege',
        'user_origin',
        'granted_by',
    ];

    /** @var array<string, string> */
    protected $casts = [
        'privilege'   => UserPrivilegeLevel::class,
        'user_origin' => UserOrigin::class,
    ];

    // ── Boot ─────────────────────────────────────────────────────────────────

    protected static function boot(): void
    {
        parent::boot();

        static::creating(static function (self $model): void {
            // Generate a custom string ID if one has not been provided already.
            if (empty($model->{$model->getKeyName()})) {
                $model->{$model->getKeyName()} = webkernel_id_generator()
                    ->makeUniqueIdentifier()
                    ->using('cuid2')
                    ->get();
            }

            // Default origin to INTERNAL when not explicitly specified.
            if ($model->user_origin === null) {
                $model->user_origin = UserOrigin::INTERNAL;
            }

            // Validate origin ↔ privilege compatibility before persisting.
            $model->user_origin->assertCompatible($model->privilege);
        });

        static::updating(static function (self $model): void {
            // Re-validate on every update so no invalid state can slip through.
            $origin  = $model->user_origin ?? UserOrigin::INTERNAL;
            $origin->assertCompatible($model->privilege);
        });
    }

    // ── Relations ─────────────────────────────────────────────────────────────

    /**
     * The user who holds this privilege.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * The user who granted this privilege.
     *
     * NULL when the privilege was self-granted (bootstrap / first APP_OWNER).
     */
    public function grantedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'granted_by');
    }

    // ── Scopes ────────────────────────────────────────────────────────────────

    /**
     * Filter by a specific privilege level.
     *
     * @param  Builder<static>             $query
     * @param  UserPrivilegeLevel|string   $privilege
     * @return Builder<static>
     */
    public function scopeForPrivilege(Builder $query, UserPrivilegeLevel|string $privilege): Builder
    {
        $value = $privilege instanceof UserPrivilegeLevel ? $privilege->value : $privilege;
        return $query->where('privilege', $value);
    }

    /**
     * Filter by user origin (internal / external).
     *
     * @param  Builder<static>    $query
     * @param  UserOrigin|string  $origin
     * @return Builder<static>
     */
    public function scopeForOrigin(Builder $query, UserOrigin|string $origin): Builder
    {
        $value = $origin instanceof UserOrigin ? $origin->value : $origin;
        return $query->where('user_origin', $value);
    }

    /** @param Builder<static> $query */
    public function scopeAppOwners(Builder $query): Builder
    {
        return $query->where('privilege', UserPrivilegeLevel::APP_OWNER->value);
    }

    /** @param Builder<static> $query */
    public function scopeSuperUsers(Builder $query): Builder
    {
        return $query->where('privilege', UserPrivilegeLevel::SUPER_ADMIN->value);
    }

    /** @param Builder<static> $query */
    public function scopeInternalUsers(Builder $query): Builder
    {
        return $query->where('user_origin', UserOrigin::INTERNAL->value);
    }

    /** @param Builder<static> $query */
    public function scopeExternalUsers(Builder $query): Builder
    {
        return $query->where('user_origin', UserOrigin::EXTERNAL->value);
    }

    /**
     * Records where the privilege was self-granted (bootstrap).
     *
     * @param Builder<static> $query
     */
    public function scopeSelfGranted(Builder $query): Builder
    {
        return $query->whereNull('granted_by')
                     ->orWhereColumn('granted_by', 'user_id');
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    public function isAppOwner(): bool
    {
        return $this->privilege === UserPrivilegeLevel::APP_OWNER;
    }

    public function isSuperAdminOrAbove(): bool
    {
        return $this->privilege->isAtLeast(UserPrivilegeLevel::SUPER_ADMIN);
    }

    public function isExternal(): bool
    {
        return $this->user_origin === UserOrigin::EXTERNAL;
    }

    public function isInternal(): bool
    {
        return $this->user_origin === UserOrigin::INTERNAL;
    }

    /**
     * Whether the privilege was self-granted (first APP_OWNER bootstrap).
     */
    public function isSelfGranted(): bool
    {
        return $this->granted_by === null
            || $this->granted_by === $this->user_id;
    }
}
