<?php declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Webkernel (v1.x.x Waterfall) core schema
 *
 * ── ID strategy ──────────────────────────────────────────────────────────────
 * All primary keys are custom string identifiers generated by
 * webkernel_id_generator() (cuid2 by default). This replaces sequential
 * auto-increment integers (1, 2, 3 …) which are predictable, easily
 * enumerable, and leak row counts. String IDs are also portable across
 * SQLite, MySQL and PostgreSQL without engine-specific sequences.
 *
 * ── Connection strategy ──────────────────────────────────────────────────────
 * This migration targets 'webkernel_sqlite' — the central SQLite file that
 * Webkernel uses for its own bootstrap, installer, and privilege system.
 *
 * At install time the APP_OWNER chooses the primary database for the
 * application. Possible paths:
 *
 * a) Stay on SQLite (default / single-file apps, rapid prototyping).
 * b) Migrate to PostgreSQL / MySQL: the installer re-runs this migration
 *    against the new connection after adjusting 'webkernel_sqlite' in
 *    config/database.php to point at that engine.  String PKs ensure zero
 *    friction; cuid2 values are valid in every engine.
 * c) Mixed: the Webkernel core tables remain on SQLite while application
 *    modules declare their own connections.  Cross-DB relationships use
 *    the string user_id as a logical key (no foreign-key constraints across
 *    connections, enforced at the application layer instead).
 *
 * Database connections are a future concern of the Webkernel installer; the
 * schema itself is intentionally agnostic.
 *
 * ── Changes ───────────────────────────────────────────────────────────────────
 * users
 *   - id: bigIncrements → char(26) (cuid2 string PK)
 *
 * user_privileges
 *   - id: bigIncrements → char(26) (cuid2 string PK)
 *   - user_id: foreignId → char(26) FK to users.id
 *   - + user_origin: varchar(20) DEFAULT 'internal'
 *       Discriminator between internal and external users.
 *       Allowed: 'internal' | 'external'
 *   - + granted_by: char(26) nullable FK to users.id
 *       The user who granted this privilege.
 *       NULL or same as user_id = self-grant (first APP_OWNER bootstrap).
 *   - + index on (privilege, user_origin) for filtered queries
 */
return new class extends Migration
{
    /**
     * Force this migration to run on the central Webkernel connection.
     *
     * Override in the host application's config/database.php if the installer
     * stores core data on a different engine (MySQL, PostgreSQL, etc.).
     */
    protected $connection = 'webkernel_sqlite';

    /**
     * cuid2 IDs are 24 characters; we use char(26) to give one character of
     * headroom for any future strategy switch (e.g. ulid = 26 chars).
     */
    private const ID_LENGTH = 26;

    // ── Up ────────────────────────────────────────────────────────────────────

    public function up(): void
    {
        // ── users ─────────────────────────────────────────────────────────────
        Schema::connection($this->connection)->create('users', function (Blueprint $table): void {
            // Custom string PK — generated by webkernel_id_generator (cuid2).
            $table->char('id', self::ID_LENGTH)->primary();

            $table->string('name');
            $table->string('email')->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->rememberToken();

            // Filament HasAvatar
            $table->string('avatar_url')->nullable();

            // Filament MFA — app (TOTP)
            $table->text('app_authentication_secret')->nullable();
            $table->text('app_authentication_recovery_codes')->nullable();

            // Filament MFA — email OTP
            $table->boolean('has_email_authentication')->default(false);

            // Webkernel QuickTouch
            $table->boolean('quick_touch_enabled')->default(true);
            $table->json('quick_touch_favorites')->nullable();

            // Position is stored client-side (localStorage).
            // $table->json('quick_touch_position')->nullable();

            $table->timestamps();
        });

        // ── user_privileges ───────────────────────────────────────────────────
        //
        // One-to-one with users: each user holds at most one privilege record.
        //
        // user_origin discriminator
        // ─────────────────────────
        // 'internal' → regular organisation member.
        // 'external' → contractor, auditor, service provider.
        //
        // Privilege constraints per origin
        // ─────────────────────────────────
        // internal  : 'app-owner' | 'super-user' | 'member'
        // external  : 'external-super-user' | 'external-member'
        // APP_OWNER is strictly reserved for internal users.
        // (The constraint is enforced at the application layer, not via a DB
        //  check constraint, to stay portable across SQLite / MySQL / PgSQL.)
        //
        // granted_by
        // ──────────
        // Tracks who assigned the privilege. For the first APP_OWNER this is
        // set to the user's own id (self-grant during bootstrap).
        // NULL is also accepted for the self-grant case and treated identically.
        Schema::connection($this->connection)->create('user_privileges', function (Blueprint $table): void {
            $table->char('id', self::ID_LENGTH)->primary();

            // user_id: unique → one privilege record per user.
            $table->char('user_id', self::ID_LENGTH)
                  ->unique();

            $table->foreign('user_id')
                  ->references('id')
                  ->on('users')
                  ->cascadeOnDelete();

            // The assigned privilege level (enum values stored as strings).
            $table->string('privilege', 30);

            // Internal vs external origin discriminator.
            $table->string('user_origin', 20)->default('internal');

            // Who granted the privilege. Nullable to support self-grant.
            $table->char('granted_by', self::ID_LENGTH)->nullable();

            $table->foreign('granted_by')
                  ->references('id')
                  ->on('users')
                  ->nullOnDelete();   // If the granting user is deleted, keep the record but clear granted_by.

            $table->timestamps();

            // Indexes for common queries.
            $table->index('privilege');
            $table->index('user_origin');
            $table->index(['privilege', 'user_origin']);
            $table->index('granted_by');
        });

        // ── password_reset_tokens ─────────────────────────────────────────────
        Schema::connection($this->connection)->create('password_reset_tokens', function (Blueprint $table): void {
            $table->string('email')->primary();
            $table->string('token');
            $table->timestamp('created_at')->nullable();
        });

        // ── sessions ──────────────────────────────────────────────────────────
        //
        // Note: sessions.user_id is a string FK referencing users.id.
        // We deliberately do NOT add a DB-level foreign key here because
        // sessions may reference users across different connections.
        Schema::connection($this->connection)->create('sessions', function (Blueprint $table): void {
            $table->string('id')->primary();
            $table->char('user_id', self::ID_LENGTH)->nullable()->index();
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();
            $table->longText('payload');
            $table->integer('last_activity')->index();
        });
    }

    // ── Down ──────────────────────────────────────────────────────────────────

    public function down(): void
    {
        Schema::connection($this->connection)->dropIfExists('sessions');
        Schema::connection($this->connection)->dropIfExists('password_reset_tokens');
        Schema::connection($this->connection)->dropIfExists('user_privileges');
        Schema::connection($this->connection)->dropIfExists('users');
    }
};
