<?php declare(strict_types=1);

defined('WEBKERNEL_SECURITY_SCORE_CRITICAL') || define('WEBKERNEL_SECURITY_SCORE_CRITICAL', 40);
defined('WEBKERNEL_SECURITY_SCORE_WARNING')  || define('WEBKERNEL_SECURITY_SCORE_WARNING',  70);
defined('WEBKERNEL_SECURITY_SCORE_GOOD')     || define('WEBKERNEL_SECURITY_SCORE_GOOD',     85);

defined('WEBKERNEL_ENV_MASK_PATTERNS') || define('WEBKERNEL_ENV_MASK_PATTERNS', [
    'key', 'secret', 'password', 'passwd', 'token', 'auth', 'pwd',
    'credential', 'private', 'cert', 'hash', 'salt', 'cipher',
    'connection_string', 'dsn', 'webhook', 'passphrase', 'pin',
]);

defined('WEBKERNEL_DANGEROUS_FUNCTIONS') || define('WEBKERNEL_DANGEROUS_FUNCTIONS', [
    'exec'                => ['score' => 100, 'category' => 'RCE',        'description' => 'Execute external program'],
    'shell_exec'          => ['score' => 100, 'category' => 'RCE',        'description' => 'Execute command via shell'],
    'system'              => ['score' => 100, 'category' => 'RCE',        'description' => 'Execute system command and display output'],
    'passthru'            => ['score' => 100, 'category' => 'RCE',        'description' => 'Execute command, pass raw output to client'],
    'popen'               => ['score' => 95,  'category' => 'RCE',        'description' => 'Open process file pointer'],
    'proc_open'           => ['score' => 95,  'category' => 'RCE',        'description' => 'Execute command with configurable stream access'],
    'pcntl_exec'          => ['score' => 100, 'category' => 'RCE',        'description' => 'Execute program replacing current PHP process'],
    'eval'                => ['score' => 100, 'category' => 'RCE',        'description' => 'Evaluate arbitrary PHP string as code'],
    'assert'              => ['score' => 85,  'category' => 'RCE',        'description' => 'Executes code when passed a string argument'],
    'create_function'     => ['score' => 95,  'category' => 'RCE',        'description' => 'Deprecated eval-based code execution vector'],
    'unserialize'         => ['score' => 95,  'category' => 'Deser',      'description' => 'PHP object deserialization — POP chain risk'],
    'FFI::cdef'           => ['score' => 100, 'category' => 'FFI',        'description' => 'Load and define C functions'],
    'FFI::load'           => ['score' => 100, 'category' => 'FFI',        'description' => 'Load C header with lib directive'],
    'FFI::scope'          => ['score' => 90,  'category' => 'FFI',        'description' => 'Access preloaded FFI scope'],
    'ffi_cdef'            => ['score' => 100, 'category' => 'FFI',        'description' => 'FFI procedural alias'],
    'file_put_contents'   => ['score' => 70,  'category' => 'Write',      'description' => 'Write arbitrary data to any accessible file'],
    'unlink'              => ['score' => 75,  'category' => 'Destroy',    'description' => 'Delete files'],
    'rmdir'               => ['score' => 70,  'category' => 'Destroy',    'description' => 'Remove directories'],
    'chmod'               => ['score' => 80,  'category' => 'Priv',       'description' => 'Change file permissions'],
    'chown'               => ['score' => 85,  'category' => 'Priv',       'description' => 'Change file ownership'],
    'symlink'             => ['score' => 75,  'category' => 'LFI',        'description' => 'Create symbolic links'],
    'file_get_contents'   => ['score' => 40,  'category' => 'LFI',        'description' => 'Read local or remote files'],
    'fopen'               => ['score' => 50,  'category' => 'LFI',        'description' => 'Open files or URLs'],
    'readfile'            => ['score' => 60,  'category' => 'LFI',        'description' => 'Output file content directly'],
    'highlight_file'      => ['score' => 70,  'category' => 'Disclosure', 'description' => 'Output PHP source code'],
    'show_source'         => ['score' => 70,  'category' => 'Disclosure', 'description' => 'Alias of highlight_file'],
    'phpinfo'             => ['score' => 75,  'category' => 'Disclosure', 'description' => 'Discloses full server configuration'],
    'var_dump'            => ['score' => 20,  'category' => 'Disclosure', 'description' => 'Debug output — must not exist in production'],
    'debug_backtrace'     => ['score' => 30,  'category' => 'Disclosure', 'description' => 'Exposes call stack'],
    'call_user_func'      => ['score' => 70,  'category' => 'Dynamic',    'description' => 'Dynamic function call'],
    'call_user_func_array'=> ['score' => 70,  'category' => 'Dynamic',    'description' => 'Dynamic function call with array arguments'],
    'extract'             => ['score' => 65,  'category' => 'Injection',  'description' => 'Variable overwrite from array'],
    'parse_str'           => ['score' => 60,  'category' => 'Injection',  'description' => 'Parse query string into variables'],
    'fsockopen'           => ['score' => 65,  'category' => 'Network',    'description' => 'Raw socket connection'],
    'putenv'              => ['score' => 55,  'category' => 'Env',        'description' => 'Modify process environment variables at runtime'],
    'ini_set'             => ['score' => 50,  'category' => 'Config',     'description' => 'Override PHP configuration at runtime'],
    'dl'                  => ['score' => 100, 'category' => 'Extension',  'description' => 'Dynamically load a PHP extension'],
    'base64_decode'       => ['score' => 20,  'category' => 'Obfuscation','description' => 'Commonly used to hide encoded payloads'],
    'md5'                 => ['score' => 30,  'category' => 'Crypto',     'description' => 'Cryptographically broken — do not use for signatures or passwords'],
    'sha1'                => ['score' => 25,  'category' => 'Crypto',     'description' => 'Weak — use SHA-256 or stronger'],
    'move_uploaded_file'  => ['score' => 65,  'category' => 'Upload',     'description' => 'Verify MIME type and extension before calling'],
    'include'             => ['score' => 70,  'category' => 'LFI',        'description' => 'Dynamic include — path traversal risk'],
    'include_once'        => ['score' => 70,  'category' => 'LFI',        'description' => 'Dynamic include_once — path traversal risk'],
    'require'             => ['score' => 70,  'category' => 'LFI',        'description' => 'Dynamic require — path traversal risk'],
    'require_once'        => ['score' => 70,  'category' => 'LFI',        'description' => 'Dynamic require_once — path traversal risk'],
    'set_include_path'    => ['score' => 55,  'category' => 'LFI',        'description' => 'Manipulate PHP include path'],
    'copy'                => ['score' => 60,  'category' => 'Write',      'description' => 'Copy files including from stream wrappers'],
    'rename'              => ['score' => 65,  'category' => 'Write',      'description' => 'Rename or move files'],
    'preg_replace'        => ['score' => 70,  'category' => 'RCE',        'description' => 'Audit for obfuscated patterns'],
    'json_decode'         => ['score' => 10,  'category' => 'Deser',      'description' => 'Always use associative array mode'],
    'socket_create'       => ['score' => 60,  'category' => 'Network',    'description' => 'Raw socket creation — SSRF risk'],
]);
