<?php declare(strict_types=1);

defined('WEBKERNEL_SLOW_REQUEST_MS')     || define('WEBKERNEL_SLOW_REQUEST_MS',     500);
defined('WEBKERNEL_SLOW_QUERY_MS')       || define('WEBKERNEL_SLOW_QUERY_MS',       100);
defined('WEBKERNEL_SLOW_JOB_MS')         || define('WEBKERNEL_SLOW_JOB_MS',         5000);

defined('WEBKERNEL_DISK_CRITICAL_BYTES') || define('WEBKERNEL_DISK_CRITICAL_BYTES', 1_073_741_824);
defined('WEBKERNEL_DISK_WARNING_BYTES')  || define('WEBKERNEL_DISK_WARNING_BYTES',  5_368_709_120);

defined('WEBKERNEL_MIN_MEMORY_LIMIT_MB') || define('WEBKERNEL_MIN_MEMORY_LIMIT_MB', 128);
defined('WEBKERNEL_REC_MEMORY_LIMIT_MB') || define('WEBKERNEL_REC_MEMORY_LIMIT_MB', 512);
defined('WEBKERNEL_MIN_MAX_EXEC_TIME')   || define('WEBKERNEL_MIN_MAX_EXEC_TIME',    30);
defined('WEBKERNEL_REC_MAX_EXEC_TIME')   || define('WEBKERNEL_REC_MAX_EXEC_TIME',    120);
defined('WEBKERNEL_MIN_UPLOAD_MAX_MB')   || define('WEBKERNEL_MIN_UPLOAD_MAX_MB',    32);
defined('WEBKERNEL_MIN_POST_MAX_MB')     || define('WEBKERNEL_MIN_POST_MAX_MB',      32);
